name: CI 
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
          branch: 'stable'
      - run: git checkout master
      - run: git pull
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: git add .
      - run: git commit -m build is successful
      - run: git push origin master
